# Generated by Django 4.1.7 on 2023-03-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='repeatpass',
        ),
    ]
