# Generated by Django 4.1.7 on 2023-03-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_signup_repeatpass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signin',
        ),
    ]
