# Generated by Django 4.1.7 on 2023-05-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_delete_signin'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=30)),
                ('pid', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'cart_table',
            },
        ),
    ]
